### PR TITLE
Max/initial migration

### PR DESCRIPTION
**Pull request by maxwellsmart84**
+ This migration has parties, favors, guests, hosts, types and typeclasses tables added as well as their many to many join tables.

+ Also moved knex file to root directoy till i can figure out how the --knexfile command works (wouldn't let me set a path).

+ Edited knexfile to look for migrations in lib.

### CODE REVIEW

**Comment by maxwellsmart84** [comment]
HOLD

**Comment by BlakeGuilloud** [comment]
Can you go ahead and add our lib folder into the .gitignore and delete it on your next push. 

Thanks

**Comment by maxwellsmart84** [comment]
removed the lib - added in the gulp task 'gulp rebuildDb"  This will drop the database, rebuild and run migrations.  PS!!! you need to run npm install and create a .env file it should look like: 

DEV_DB_NAME=schindigDB
DEV_DB_USERNAME=root
DEV_DB_PASS=

for local serving - Then you can gulp start it

**Comment by BlakeGuilloud** [comment]
This ready for master?

**Comment by maxwellsmart84** [comment]
@BlakeGuilloud yeah buddy

**Pull request merged**
